@startuml JeuDeRole

skinparam classAttributeIconSize 0

' ===== CLASSES PRINCIPALES =====
class Jeu {
  - donjons: List<Donjon>
  - joueurs: List<Personnage>
  - maitreDuJeu: MaitreDuJeu
  + demarrer()
  + finPartie()
}

class MaitreDuJeu {
  + narrer()
  + decrireContexte()
  + creerMonstres()
  + positionnerElements()
}

package carteDuJeu{

    class Donjon {
        - carte: Carte
        - monstres: List<Monstre>
        - equipements: Equipement[*]
        - joueurs: List<Personnage>
        + miseEnPlace()
        + deroulerCombat()
        + finDonjon()
    }
    class Des{
        - {static} final random : Random
        + {static}  lancer( notation : String) : Integer
        + {static}  lancer( nbFaces : Integer) : Integer
        + {static} lancer( nbDes : Integer,  nbFaces: int) : Integer
    }
    class Carte {
      - largeur: Integer
      - hauteur: Integer
      - cases: Case[][]
      + afficherCarte()
    }

    class Case {
      - x: Integer
      - y: Integer
      - estObstacle: Boolean
      - contient: List<Object>
    }

    package personnages {
        class Personnage {
            - m_nom : String
            - m_pointsDeVie : Integer
            - m_pointsDeVieMax : Integer
            - m_forceBase : Integer
            - m_forceCurrent : Integer
            - m_dexteriteBase : Integer
            - m_vitesseBase : Integer
            - m_vitesseCurrent : Integer
            - m_initiativeBase : Integer

            + Personnage(nom: String, race: Race, classe: Classe)
            + getNom() : String
            + getRace() : String
            + getClasse() : String
            + getPointsDeVie() : Integer
            + getPointsDeVieMax() : Integer
            + getForce() : Integer
            + getDexterite() : Integer
            + getVitesse() : Integer
            + getInitiative() : Integer
            + getInventaire() : Equipement[*]
            + getArmeEquipee() : Arme
            + getArmureEquipee() : Armure
            + setArmeEquipee(index: Integer) : Boolean
            + setArmureEquipee(index: Integer) : Boolean
            + getCasesMaxDeplacement() : Integer
        }
    package races {
             abstract class Race {
                - m_nomRace : String
                - m_forceBonus : Integer
                - m_dexteriteBonus : Integer
                - m_vitesseBonus : Integer
                - m_initiativeBonus : Integer

                + getNomRace() : String
                + getForceBonus() : Integer
                + getDexteriteBonus() : Integer
                + getVitesseBonus() : Integer
                + getInitiativeBonus() : Integer
            }
            class Elfe extends Race{
                + Elfe()
            }
            class Humain extends Race{
                            + Humain()
                        }
            class Nain extends Race{
                            + Nain()
                        }
            class Halfelin extends Race{
                            + Halfelin()
                        }
        }
        package classes
        {
            abstract class Classe {
                - m_nomClasse : String
                - m_pointsDeVie : Integer
                - m_forceBonus : Integer
                - m_dexteriteBonus : Integer
                - m_initiativeBonus : Integer

                + getNomClasse() : String
                + getPointsDeVie() : Integer
                + getForceBonus() : Integer
                + getDexteriteBonus() : Integer
                + getInitiativeBonus() : Integer
                + {abstract} getEquipementInitial() : Equipement[*]
            }
            class Clerc extends Classe{
                + Clerc()
                + getEquipementInitial() : Equipement[*]
            }
            class Guerrier extends Classe{
                            + Guerrier()
                            + getEquipementInitial() : Equipement[*]
                        }
            class Magicien extends Classe{
                            + Magicien()
                            + getEquipementInitial() : Equipement[*]
                        }
            class Roublard extends Classe{
                            + Roublard()
                            + getEquipementInitial() : Equipement[*]
                        }

        }

        ' ==== Equipements =====


        }
    }
    package carteDuJeu.personnages.equipements.armes{
                        abstract class Arme extends carteDuJeu.personnages.equipements.Equipement {
                             - m_degats : String
                             - m_portee : Integer
                             - m_estLourde : Boolean

                             + getDegats() : String
                             + getPortee() : Integer
                             + estLourde() : Boolean
                             + toString() : String
                            }
                        class ArbaleteLegere extends Arme{
                            + ArbaleteLegere()
                            }
                        class ArcCourt extends Arme{
                                        + ArcCourt()
                                    }
                        class Baton extends Arme{
                                        + Baton()
                                                }
                        class Fronde extends Arme{
                                        + Fronde()
                                                }
                        class EpeeLongue extends Arme{
                                        + EpeeLongue()
                                                }
                        class MasseDarmes extends Arme{
                                        + MasseDarmes()
                                                }
                        class Rapiere extends Arme{
                                        + Rapiere()
                                                }
                    }
package carteDuJeu.personnages.equipements{
        abstract class Equipement {
            - m_nom : String

            + Equipement(nom : String)
            + getNom() : String
        }
}
package carteDuJeu.personnages.equipements.armures{

                abstract class Armure extends carteDuJeu.personnages.equipements.Equipement {
                                - m_classeArmure : Integer
                                - m_estLourde : Boolean

                                + getClasseArmure() : Integer
                                + estLourde() : Boolean
                                + toString() : String
                            }

                class Harnois extends Armure{
                                + Harnois()
                }
                class ArmureDEcailles extends Armure{
                                 + ArmureDEcailles()
                            }
                class CotteDeMailles extends Armure{
                                 + CotteDeMailles()
                            }
                class DemiPlate extends Armure{
                                 + DemiPlate()
                            }
}
    ' ===== MONSTRES =====
    package carteDuJeu.Monstres {
        class Monstre {
          - espece : String
            - numero : Integer
            - attaque : Attaque
            - pointsDeVie : Integer
            - force : Integer
            - dexterite : Integer
            - classeArmure : Integer
            - initiative : Integer
            + Monstre(espece : String, numero : Integer, attaque : Attaque, pointsDeVie : Integer, force : Integer, dexterite : Integer, classeArmure : Integer, initiative : Integer)
            + attaquer(cible : Personnage)
            + getEspece() : String
            + setEspece(espece : String)
            + getNumero() : Integer
            + setNumero(numero : Integer)
            + getAttaque() : Attaque
            + setAttaque(attaque : Attaque)
            + getPointsDeVie() : Integer
            + setPointsDeVie(pointsDeVie : Integer)
            + getForce() : Integer
            + setForce(force : Integer)
            + getDexterite() : Integer
            + setDexterite(dexterite : Integer)
            + getClasseArmure() : Integer
            + setClasseArmure(classeArmure : Integer)
            + getInitiative() : Integer
            + setInitiative(initiative : Integer)
        }

        class Attaque {
          - m_degats : String
            - m_portee : Integer
            + Attaque(degats : String, portee : Integer)
            + getDegats() : String
            + getPortee() : Integer
            + estCorpsACorps() : Boolean
            + toString() : String
        }
    }



' ===== RELATIONS =====
Jeu --> Donjon
Jeu --> Personnage
Jeu --> MaitreDuJeu

Donjon --> Carte
Donjon --> Monstre
Donjon --> Equipement
Donjon --> Personnage

Carte --> Case
Case --> Equipement
Case --> Monstre
Case --> Personnage




Personnage o-> "\n 0..* \n- m_inventaire" Equipement : < peut être mis dans l'inventaire
Personnage o-> "\n 0..1 \n- m_armeEquipee" Arme : < portée par
Personnage o-> "\n 0..1 \n- m_armureEquipee" Armure : < portée par

Personnage ..> Des : <<uses>>

Personnage --> "\n 0..1 \n- m_race"  Race
Personnage --> "\n 0..1 \n- m_classe" Classe

Monstre --> Attaque



@enduml