@startuml JeuDeRole

skinparam classAttributeIconSize 0

' ===== CLASSES PRINCIPALES =====
class Jeu {
  - donjons: List<Donjon>
  - joueurs: List<Personnage>
  - maitreDuJeu: MaitreDuJeu
  + demarrer()
  + finPartie()
}

class MaitreDuJeu {
  + narrer()
  + decrireContexte()
  + creerMonstres()
  + positionnerElements()
}

package carteDuJeu{

    class Donjon {
        - carte: Carte
        - monstres: List<Monstre>
        - equipements: Equipement[*]
        - joueurs: List<Personnage>
        + miseEnPlace()
        + deroulerCombat()
        + finDonjon()
    }
    class Des{
        - {static} final random : Random
        + {static}  lancer( notation : String) : Integer
        + {static}  lancer( nbFaces : Integer) : Integer
        + {static} lancer( nbDes : Integer,  nbFaces: int) : Integer
    }
    class Carte {
      - largeur: Integer
      - hauteur: Integer
      - cases: Case[][]
      + afficherCarte()
    }

    class Case {
      - x: Integer
      - y: Integer
      - estObstacle: Boolean
      - contient: List<Object>
    }

    package personnages {
        class Personnage {
            - m_nom : String
            - m_pointsDeVie : Integer
            - m_pointsDeVieMax : Integer
            - m_forceBase : Integer
            - m_forceCurrent : Integer
            - m_dexteriteBase : Integer
            - m_vitesseBase : Integer
            - m_vitesseCurrent : Integer
            - m_initiativeBase : Integer

            + Personnage(nom: String, race: Race, classe: Classe)
            + getNom() : String
            + getRace() : String
            + getClasse() : String
            + getPointsDeVie() : Integer
            + getPointsDeVieMax() : Integer
            + getForce() : Integer
            + getDexterite() : Integer
            + getVitesse() : Integer
            + getInitiative() : Integer
            + getInventaire() : Equipement[*]
            + getArmeEquipee() : Arme
            + getArmureEquipee() : Armure
            + setArmeEquipee(index: Integer) : Boolean
            + setArmureEquipee(index: Integer) : Boolean
            + getCasesMaxDeplacement() : Integer
            + getSymbole() : String
            + subirDegats(degats : Integer)
            + estMort()
            + recalculerStats()
        }
    package races {
             abstract class Race {
                - m_nomRace : String
                - m_forceBonus : Integer
                - m_dexteriteBonus : Integer
                - m_vitesseBonus : Integer
                - m_initiativeBonus : Integer

                + Race(m_nomRace: String, m_forceBonus : Integer, m_dexteriteBonus: Integer, m_vitesseBonus : Integer, m_initiativeBonus : Integer)
                + getNomRace() : String
                + getForceBonus() : Integer
                + getDexteriteBonus() : Integer
                + getVitesseBonus() : Integer
                + getInitiativeBonus() : Integer
            }
            class Elfe extends Race{
                + Elfe()
            }
            class Humain extends Race{
                            + Humain()
                        }
            class Nain extends Race{
                            + Nain()
                        }
            class Halfelin extends Race{
                            + Halfelin()
                        }
        }
        package classes
        {
            abstract class Classe {
                - m_nomClasse : String
                - m_pointsDeVie : Integer
                - m_forceBonus : Integer
                - m_dexteriteBonus : Integer
                - m_initiativeBonus : Integer

                + Classe(m_nomClasse: String, m_forceBonus : Integer, m_dexteriteBonus: Integer, m_vitesseBonus : Integer, m_initiativeBonus : Integer)
                + getNomClasse() : String
                + getPointsDeVie() : Integer
                + getForceBonus() : Integer
                + getDexteriteBonus() : Integer
                + getInitiativeBonus() : Integer
                + getEquipementInitial() : Equipement[*]
                #  {abstract} initialiserEquipement()
            }
            class Clerc extends Classe{
                + Clerc()
                + getEquipementInitial() : Equipement[*]
            }
            class Guerrier extends Classe{
                            + Guerrier()
                            + getEquipementInitial() : Equipement[*]
                        }
            class Magicien extends Classe{
                            + Magicien()
                            + getEquipementInitial() : Equipement[*]
                        }
            class Roublard extends Classe{
                            + Roublard()
                            + getEquipementInitial() : Equipement[*]
                        }

        }

        ' ==== Equipements =====


        }
    }
    package carteDuJeu.personnages.equipements.armes{
                        abstract class Arme extends carteDuJeu.personnages.equipements.Equipement {
                             - m_degats : String
                             - m_portee : Integer
                             - m_estLourde : Boolean

                             +Arme( m_nom : String,  m_degats : String,  m_portee : Integer,  m_estLourde : Boolean)
                             + getDegats() : String
                             + getPortee() : Integer
                             + estLourde() : Boolean
                             + toString() : String
                            }
                        class ArbaleteLegere extends Arme{
                            + ArbaleteLegere()
                            }
                        class ArcCourt extends Arme{
                                        + ArcCourt()
                                    }
                        class Baton extends Arme{
                                        + Baton()
                                                }
                        class Fronde extends Arme{
                                        + Fronde()
                                                }
                        class EpeeLongue extends Arme{
                                        + EpeeLongue()
                                                }
                        class MasseDarmes extends Arme{
                                        + MasseDarmes()
                                                }
                        class Rapiere extends Arme{
                                        + Rapiere()
                                                }
                    }
package carteDuJeu.personnages.equipements{
        abstract class Equipement {
            - m_nom : String

            + Equipement(nom : String)
            + getNom() : String
        }
}
package carteDuJeu.personnages.equipements.armures{

                abstract class Armure extends carteDuJeu.personnages.equipements.Equipement {
                                - m_classeArmure : Integer
                                - m_estLourde : Boolean

                                + getClasseArmure() : Integer
                                + estLourde() : Boolean
                                + toString() : String
                            }

                class Harnois extends Armure{
                                + Harnois()
                }
                class ArmureDEcailles extends Armure{
                                 + ArmureDEcailles()
                            }
                class CotteDeMailles extends Armure{
                                 + CotteDeMailles()
                            }
                class DemiPlate extends Armure{
                                 + DemiPlate()
                            }
}
    ' ===== MONSTRES =====
    package carteDuJeu.Monstres {
        class Monstre implements carteDuJeu.Carte{
            - String m_espece
            - Integer m_numero
            - Integer m_portee
            - Integer m_maxDmg
            - Integer m_nbDes
            - Integer m_pointsDeVieMax
            - Integer m_pointsDeVie
            - Integer m_force
            - Integer m_dexterite
            - Integer m_vitesse
            - Integer m_classeArmure
            - Integer m_initiative

            + Monstre(String espece, Integer numero, Integer portee, Integer maxDmg, Integer vitesse, Integer nbDes, Integer pointsDeVieMax, Integer caracteristiqueDAttaque, Integer classeArmure, Integer initiative)

            + String getEspece()
            + void setEspece(String espece)
            + Integer getNumero()
            + void setNumero(Integer numero)
            + Integer getM_maxDmg()
            + Integer getNbDes()
            + void setMaxdmg(Integer dmgMax, Integer nbDes)
            + Integer getPortee()
            + Integer getCasesMaxDeplacement()
            + void setVitesse(Integer vitesse)
            + void setPorteeEtStat(Integer portee, Integer caracteristiqueDAttaque)
            + void changementCarac(Integer caracteristiqueDAttaque)
            + Integer getPointsDeVie()
            + void setPointsDeVieMax(Integer pointsDeVie)
            + Integer getPointsDeVieMax()
            + Integer getForce()
            + Integer getDexterite()
            + Integer getClasseArmure()
            + void setClasseArmure(Integer classeArmure)
            + Integer getInitiative()
            + void setInitiative(Integer initiative)

            + String getSymbole()
            + String getNom()
            + subirDegats(degats : Integer)
            + estMort()
        }

        class Attaque {
          +attaquer(carte : Carte, attaquant : Personnage, cible : Monstre, caseAttaquant : Case, caseCible : Case) : Boolean
          +attaquer(carte : Carte, attaquant : Monstre, cible : Personnage, caseAttaquant : Case, caseCible : Case) : Boolean
          - {static} calculDistance() : Integer
        }
    }



' ===== RELATIONS =====
Jeu --> Donjon
Jeu --> Personnage
Jeu --> MaitreDuJeu

Donjon --> Carte
Donjon --> Monstre
Donjon --> Equipement
Donjon --> Personnage

Carte --> Case
Case --> Equipement
Case --> Monstre
Case --> Personnage

Classe "1" o-- "0..*" Equipement : m_equipementInitial


Personnage o-> "\n 0..* \n- m_inventaire" Equipement : < peut être mis dans l'inventaire
Personnage o-> "\n 0..1 \n- m_armeEquipee" Arme : < portée par
Personnage o-> "\n 0..1 \n- m_armureEquipee" Armure : < portée par

Personnage ..> Des : <<uses>>

Personnage --> "\n 0..1 \n- m_race"  Race
Personnage --> "\n 0..1 \n- m_classe" Classe

Attaque ..> Carte : utilise
Attaque ..> Case : utilise
Attaque ..> Personnage : utilise
Attaque ..> Monstre : utilise
Attaque ..> Arme : utilise
Attaque ..> Armure : utilise
Attaque ..> Des : <<uses>>



@enduml